
version: '3.8'

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pgnetwork

  # Serviço PgAdmin4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  # Volume persistente para dados do PostgreSQL
  pg_data:
    driver: local
  # Volume persistente para dados do PgAdmin4
  pgadmin_data:
    driver: local

networks:
  pgnetwork:
    driver: bridge
